plugins {
	id "fabric-loom" version "${loom_version}"
	id "maven-publish"
}

version = "${mod_version}+mc${minecraft_version}"
group = maven_group

base {
	archivesName = "${archives_base_name}-fabric"
}

repositories {
	mavenLocal()
}

sourceSets {
	main {
		java.srcDirs = ["common/src/main/java", "fabric/src/main/java"]
		resources.srcDirs = ["common/src/main/resources", "fabric/src/main/resources"]
	}
	test {
		java.srcDirs = ["common/src/test/java"]
	}
}

loom {
	accessWidenerPath = file("common/src/main/resources/villagersplus.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
	modImplementation("lion.villagertradingplus:villagertradingplus-fabric:${villagertradingplus_version}+mc${minecraft_version}") {
		changing = true
	}

	testImplementation platform("org.junit:junit-bom:5.10.2")
	testImplementation "org.junit.jupiter:junit-jupiter"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

configurations.configureEach {
	resolutionStrategy.cacheChangingModulesFor 0, "seconds"
}

tasks.named("test") {
	useJUnitPlatform()
}

processResources {
	def v = project.version
	inputs.property "version", v
	filesMatching("fabric.mod.json") {
		expand "version": v
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.release = 21
}

java {
	withSourcesJar()
}

publishing {
	publications {
		mavenFabric(MavenPublication) {
			artifactId = "${archives_base_name}-fabric"
			from components.java
		}
	}
}
